name: Criminal Records
main: me.fred50.criminal.CriminalRecords
version: 1.3
description: >
             Dodatek dodajacy liste poszukiwanych przestepcow
commands:
  cr:
    description: Pokazuje liste komend.