name: Criminal Records (PL)
main: me.fred50.criminal.CriminalRecords
version: 1.2
description: >
             Dodatek dodajacy liste poszukiwanych przestepcow.
commands:
  cr:
    description: Pokazuje liste komend.